import type { Metadata } from "next";
import { Tektur } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const tektur = Tektur({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Космомиссия",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${tektur.variable} antialiased bg-black`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
